#!/usr/bin/env python3
"""
EHBA ruleset — build-time preprocessor (iA Writer Markdown -> kramdown-clean).

The source Markdown is the single source of truth and stays iA-Writer-compatible
(for PDF export). This script produces a DERIVED file for GitHub Pages / Jekyll.
The source is never modified.

Why this is needed
------------------
iA Writer nests tab-indented ordered lists with multi-digit manual markers
(311., 3121.). kramdown/CommonMark instead decide nesting by MARKER WIDTH, so
those tab-indented lists collapse into flat text and the CSS-counter numbering
breaks. This script rebuilds the nesting from the TAB DEPTH and normalises every
ordered marker to "1." (the visible clause number is regenerated by
style-ruleset.css from nesting depth, so the literal digits are irrelevant).

Transformations
---------------
  1. `# Heading [sectionN]`  -> `# Heading {#sectionN}`  (kramdown heading IDs)
  2. `[Text][sectionN]`      -> `[Text](#sectionN)`      (ref link -> anchor link)
  3. `{{TOC}}`               -> generated bullet list in <div class="TOC">
  4. `+++`                   -> removed (PDF page breaks; web view scrolls)
  5. tab-indented lists      -> 3 spaces/level, ordered markers normalised to "1."

Usage:  python3 build_page.py SOURCE.md > OUT.md
"""
import re
import sys

INDENT = "   "  # 3 spaces per nesting level (>= "1." + space)


def transform(text: str) -> str:
    lines = text.split("\n")

    # Pass 1 — collect H1 section headings for the TOC
    sections = []
    for l in lines:
        m = re.match(r'^#\s+(.*?)\s*\[(section\d+)\]\s*$', l)
        if m:
            sections.append((m.group(1), m.group(2)))

    out = []
    for l in lines:
        # (2) reference-style links -> anchor links
        l = re.sub(r'\]\[(section\d+|diagram\d+)\]', r'](#\1)', l)
        stripped = l.strip()

        # (4) drop iA page-break markers
        if stripped == "+++":
            continue

        # (3) expand the TOC macro
        if stripped == "{{TOC}}":
            out.append('<div class="TOC" markdown="1">')
            out.append("")
            out.append("- [EHBA Regolamento Ufficiale](#top)")
            for title, sid in sections:
                clean = re.sub(r'[*_`]', '', title)
                out.append(f"- [{clean}](#{sid})")
            out.append("")
            out.append("</div>")
            continue

        # (1) iA heading IDs -> explicit anchor + kramdown {#id}
        #     The <a id> works in ANY renderer; the {#id} keeps the heading itself
        #     addressable in kramdown. Both point to the same fragment.
        mh = re.match(r'^(#{1,6})(\s+.*?)\s*\[(section\d+|diagram\d+)\]\s*$', l)
        if mh:
            hid = mh.group(3)
            out.append(f'<a id="{hid}"></a>')
            out.append("")
            out.append(f'{mh.group(1)}{mh.group(2)} {{#{hid}}}')
            continue

        # (5) re-indent tab-based list lines
        mt = re.match(r'^(\t*)(.*)$', l)
        depth, rest = len(mt.group(1)), mt.group(2)
        if depth == 0 and not re.match(r'^\d+\.\s', rest) and not rest.startswith("- "):
            out.append(l)
            continue

        pad = INDENT * depth
        mo = re.match(r'^(\d+)\.\s+(.*)$', rest)
        mb = re.match(r'^-\s+(.*)$', rest)
        if mo:
            out.append(f'{pad}1. {mo.group(2)}')
        elif mb:
            out.append(f'{pad}- {mb.group(1)}')
        else:
            out.append(pad + rest if rest else "")

    return "\n".join(out)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.stderr.write("usage: build_page.py SOURCE.md > OUT.md\n")
        sys.exit(1)
    with open(sys.argv[1], encoding="utf-8") as f:
        sys.stdout.write(transform(f.read()))
