#!/usr/bin/env python3
"""Generate assets/css/style-fonts.css with the theme's faces inlined.

The fonts are base64-embedded on purpose: the CSS is used both by the web build
(assets/css/) and by the iA Writer PDF template (tpl/.../Contents/Resources/),
which sit at different depths, so a url() path could not be identical in both
copies. Inlining keeps the two files byte-for-byte the same and guarantees the
PDF export resolves the faces. Re-run this script if a font file changes.
"""
import base64
import pathlib
import shutil

ROOT = pathlib.Path(__file__).resolve().parent

# (CSS family name, file in assets/fonts/, font-weight, font-style)
FACES = [
    ("Inter", "Inter-Regular.woff2", 400, "normal"),
    # The only SF Mono cut in the repo is Medium; declared truthfully so the
    # weight is not lied about — it is the sole face of its family, so it is
    # still used for every requested weight (bold is synthesised, as before).
    ("SF Mono", "SF-Mono-Medium.otf", 500, "normal"),
]

# Extension -> (data: URI MIME type, CSS format() hint)
FORMATS = {
    ".woff2": ("font/woff2", "woff2"),
    ".woff": ("font/woff", "woff"),
    ".otf": ("font/otf", "opentype"),
    ".ttf": ("font/ttf", "truetype"),
}

HEADER = """/*
 * Webfonts for the ruleset — shared by the web build and the iA Writer PDF
 * template. GENERATED by gen_fonts_css.py; do not hand-edit.
 *
 * The font files (assets/fonts/) are base64-inlined so this file is identical
 * in both copies: assets/css/ and tpl/EHBA-Ruleset.iatemplate/Contents/
 * Resources/ sit at different depths, so no single url() path would work for
 * both, and the PDF exporter is guaranteed to find the faces.
 */

"""

VARS = """
/* Family stacks used across the theme, plus the OpenType features the body face
   is set with. Applied in style-ruleset.css; they live here because they are a
   property of the face, so swapping the font swaps its features with it. */
:root {
\t--font-body: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica,
\t\tArial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
\t--font-mono: "SF Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo,
\t\tCourier, monospace;
\t--font-body-features: "cv09", "cv01", "cv06", "cv10", "calt", "case", "cv08",
\t\t"dlig", "ss01", "ss07", "ss08", "zero";
}
"""


def main() -> None:
    out = [HEADER]
    for family, filename, weight, style in FACES:
        path = ROOT / "assets" / "fonts" / filename
        mime, fmt = FORMATS[path.suffix.lower()]
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        out.append(
            "@font-face {\n"
            f'\tfont-family: "{family}";\n'
            f"\tfont-style: {style};\n"
            f"\tfont-weight: {weight};\n"
            "\tfont-display: swap;\n"
            f'\tsrc: url("data:{mime};base64,{b64}") format("{fmt}");\n'
            "}\n"
        )
    out.append(VARS)
    css = "\n".join(out)

    web = ROOT / "assets" / "css" / "style-fonts.css"
    web.write_text(css, encoding="utf-8")
    tpl = (
        ROOT
        / "tpl"
        / "EHBA-Ruleset.iatemplate"
        / "Contents"
        / "Resources"
        / "style-fonts.css"
    )
    shutil.copyfile(web, tpl)
    print(f"wrote {web} ({web.stat().st_size} bytes)")
    print(f"mirrored to {tpl}")


if __name__ == "__main__":
    main()
